apiVersion: batch/v1
kind: CronJob
metadata:
  name: simple-scheduled-task
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: task-container
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the CronJob
          restartPolicy: OnFailure