apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        env:
        - name: MY_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: secret-key
        - name: ANOTHER_SECRET
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: another-key
        ports:
        - containerPort: 80